# Generated by Django 4.2.6 on 2023-11-05 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_album_artist_song_album_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('CollegeID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('strength', models.IntegerField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp1.artist'),
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('CollegeID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp1.college')),
            ],
        ),
    ]
