# Generated by Django 4.2.6 on 2023-11-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_college_alter_album_artist_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.IntegerField(primary_key=True, serialize=False)),
                ('Qualification', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Subjectcode', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('credits', models.IntegerField()),
                ('teacher', models.ManyToManyField(to='myapp1.teacher')),
            ],
        ),
    ]
