# Generated by Django 4.2.6 on 2023-11-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_rename_course_menuitems_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='name',
            new_name='item_name',
        ),
    ]
