# Generated by Django 4.2.6 on 2023-11-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_rename_name_menuitems_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='course',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
